server:
  port: 8083

spring:
  application:
    name: shipping_service

  datasource:
    url: jdbc:postgresql://localhost:5432/shipping_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipping-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

outbox:
  topic: shipping-events
  polling-ms: 200

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace   # 파라미터 바인딩 로그(너무 시끄러우면 info로)
